# Site settings
title: Welcome!
author:
  name: Marcos Martinez Sugastti
  email: martinezsugastti@ucdavis.edu
description: "My personal site."
twitter_username: marcoscosm

# Build settings
remote_theme: jekyll/minima
